name: aiTesting2Env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pillow=10.2.0
  - scipy=1.12.0
  - matplotlib
  - pandas=2.2.0
  - seaborn=0.13.2
  - scikit-learn=1.4.1.post1
  - numpy
  - skl2onnx
  - onnxruntime
  - onnx
  - statsmodels
  - xgboost
  - onnxmltools
  - pydot
  - pyquicksetup
  - mlprodict
  - pip
  - ipykernel
  - pip:
    - tensorflow==2.15.0
    - uuid==1.30
    - aif360